[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cosmock"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "numpy>=2.0",
    "scipy>=1.15",
    "joblib>=1.2",
    "healpy>=1.16",
]

[tool.setuptools.packages.find]
where = ["."]
